In [1]:
#Name: Bhavana Pasula 
#Course: Human Computer Interaction
#Exam03: Problem 02
#Worked on file name: Exam03_data_01


import numpy as x
import pandas as y
import matplotlib.pyplot as plt

header_list = ["one"]

DesignA_time=y.read_csv('data_01/A/Time/task_time.csv',names =header_list)

DesignB_time=y.read_csv('data_01/B/Time/task_time.csv',names =header_list)


In [2]:
DA_time=DesignA_time.one.str.split(expand=True,)
DAint_time= DA_time.astype(str).astype(int)
DAstd_time=DAint_time.std()

DB_time=DesignB_time.one.str.split(expand=True,)
DBint_time= DB_time.astype(str).astype(int)
DBstd_time=DBint_time.std()

In [3]:
Astdarr= DAstd_time.to_numpy()

Astdarr

array([10.41274964, 15.24428802, 19.48962851])

In [4]:
Bstdarr=DBstd_time.to_numpy()

Bstdarr

array([122.60619799,  29.5044906 ,  32.77433847])

In [5]:
preferred_design_time= x.where(Astdarr < Bstdarr, 'design A', 'design B')

preferred_design_time

array(['design A', 'design A', 'design A'], dtype='<U8')

In [6]:
header_list = ["one"]

DesignA_error=y.read_csv('data_01/A/Error/task_error.csv',names =header_list)

DesignB_error=y.read_csv('data_01/B/Error/task_error.csv',names =header_list)



DA_error=DesignA_error.one.str.split(expand=True,)
DAint_error= DA_error.astype(str).astype(int)
DAmean_error=DAint_error.mean()

DB_error=DesignB_error.one.str.split(expand=True,)
DBint_error= DB_error.astype(str).astype(int)
DBmean_error=DBint_error.mean()


In [7]:
Ameanarr= DAmean_error.to_numpy()
Ameanarr

array([3.03466667, 4.014     , 4.02333333])

In [8]:
Bmeanarr= DBmean_error.to_numpy()
Bmeanarr

array([2.992     , 1.00733333, 3.98733333])

In [9]:
preferred_design_error= x.where(Ameanarr < Bmeanarr, 'design A', 'design B')

preferred_design_error

array(['design B', 'design B', 'design B'], dtype='<U8')

In [10]:
preferred_design_final = [0 for i in range(len(preferred_design_error))]

for n in range(len(preferred_design_time)):
    if preferred_design_time [n] == preferred_design_error[n]:
        preferred_design_final[n] = preferred_design_time[n]
    else:
        preferred_design_final[n]= preferred_design_error[n]
        
preferred_design_final

['design B', 'design B', 'design B']

In [11]:
#Preferred design for task j is perferred_design_final[j-1]

In [12]:
A=0
B=0

for n in range(len(preferred_design_final)):
    if preferred_design_final[n] == "design A":
          A = A+1
    else:
          B =B+1

In [13]:
len(preferred_design_final)

3

In [14]:
A

0

In [15]:
B

3

In [16]:
if A>B:
    print("design A is preferred")
else:
    print("design B is preferred")

design B is preferred
